import { Currency, CurrencyConfig, Language } from '../types';

export const CURRENCY_CONFIGS: Record<Currency, CurrencyConfig> = {
  EUR: {
    code: 'EUR',
    symbol: '€',
    rate: 1.0,
    nameAr: 'يورو (€)',
    nameEn: 'Euro (€)'
  },
  USD: {
    code: 'USD',
    symbol: '$',
    rate: 1.08,
    nameAr: 'دولار أمريكي ($)',
    nameEn: 'US Dollar ($)'
  },
  AED: {
    code: 'AED',
    symbol: 'د.إ',
    rate: 3.97,
    nameAr: 'درهم إماراتي (د.إ)',
    nameEn: 'UAE Dirham (AED)'
  },
  SAR: {
    code: 'SAR',
    symbol: 'ر.س',
    rate: 4.05,
    nameAr: 'ريال سعودي (ر.س)',
    nameEn: 'Saudi Riyal (SAR)'
  }
};

export function formatPrice(priceInEur: number, currency: Currency = 'EUR'): string {
  const config = CURRENCY_CONFIGS[currency] || CURRENCY_CONFIGS.EUR;
  const converted = priceInEur * config.rate;
  return `${converted.toFixed(2)} ${config.symbol}`;
}

export const DICTIONARY = {
  ar: {
    storeName: 'Barakamarkt Greifswald',
    storeSubtitle: 'بركة ماركت غرايفسفالد - بقالية ومؤونة المدن السورية الأصيلة',
    searchPlaceholder: 'ابحث عن جبنة حموية، فريكة حلب، مكدوس دمشقي، زيت عفرين...',
    allCategories: 'كافة الأقسام (14 قسم منظم)',
    freshColdDeliveryBadge: 'شحن مبرد طازج للألبان والأجبان',
    freeShippingNotice: '⚡ توصيل سريع خلال ساعتين عمل في غرايفسفالد (مجاني للطلبات فوق 25€)',
    addToCart: 'إضافة للسلة',
    inStock: 'متوفر في غرايفسفالد',
    outOfStock: 'نفد من المخزن',
    piecesLeft: 'قطعة متبقية فقط',
    quickView: 'عرض التفاصيل',
    coldChain: 'شحن مبرد معزول',
    halal: 'حلال 100%',
    organic: 'مؤونة بلدية سورية',
    cartTitle: 'سلة المشتريات',
    emptyCart: 'سلة التسوق فارغة حالياً',
    emptyCartDesc: 'تصفح مؤونة المدن السورية وأضف طلبك ليصلك في غرايفسفالد خلال ساعتين!',
    subtotal: 'المجموع الفرعي',
    shipping: 'توصيل محلي بغرايفسفالد',
    freeShipping: 'توصيل مجاني',
    freeShippingRemaining: 'أضف بقيمة {amount} للحصول على توصيل مجاني بغرايفسفالد!',
    freeShippingAchieved: 'مبروك! طلبك مؤهل للتوصيل المجاني السريع 🎁',
    coldPackagingFee: 'تغليف حراري مبرد للأجبان',
    total: 'الإجمالي النهائي',
    checkout: 'إتمام الطلب والتوصيل السريع',
    continueShopping: 'متابعة التسوق',
    applyCoupon: 'تطبيق الخصم',
    couponCode: 'كوبون الخصم (جرب: GREIF24)',
    couponApplied: 'تم تطبيق خصم 10% بنجاح!',
    origin: 'المدينة والمنشأ في سوريا',
    brand: 'العلامة التجارية',
    unitWeight: 'الوزن والعبوة',
    ingredients: 'المكونات',
    storageInstructions: 'طريقة الحفظ',
    chefAIButton: 'شيف المؤونة الذكي 👨‍🍳',
    recipeKitsTitle: 'سلات الطبخات والمؤونة السورية',
    recipeKitsSubtitle: 'مجموعات متكاملة بنقرة واحدة لتحضير أشهى المأكولات السورية وتوصيلها خلال ساعتين',
    addKitToCart: 'إضافة كل المكونات للسلة',
    trackOrder: 'تتبع طلبي في غرايفسفالد',
    filterBy: 'تصفية حسب',
    sortBy: 'الترتيب حسب',
    sortDefault: 'المقترح والمميز',
    sortPriceAsc: 'السعر: من الأقل للأعلى',
    sortPriceDesc: 'السعر: من الأعلى للأقل',
    sortRating: 'الأعلى تقييماً',
    allOrigins: 'كافة المدن السورية',
    coldFilterOnly: 'منتجات التبريد فقط ❄️',
    dealsOnly: 'العروض والخصومات فقط 🏷️',
    guarantees: {
      coldDelivery: 'توصيل مبرد طازج',
      coldDeliverySub: 'تغليف حراري مع أكياس ثلج يحافظ على الأجبان طازجة',
      fastShipping: 'توصيل خلال ساعتين عمل ⚡',
      fastShippingSub: 'مندوبنا في غرايفسفالد يوصل لباب بيتك مباشرة',
      authentic: 'مستورد من المدن السورية',
      authenticSub: 'أجبان حماة، زيتون وزيت حلب وعفرين، بن وتوابل الشام',
      support: 'خدمة محلية عبر واتساب',
      supportSub: 'تواصل مباشر لتنسيق موعد وموقع الاستلام في غرايفسفالد'
    }
  },
  en: {
    storeName: 'Barakamarkt Greifswald',
    storeSubtitle: 'Barakamarkt Greifswald - Authentic Syrian Grocery & Local Express Delivery',
    searchPlaceholder: 'Search Hama cheese, Aleppo freekeh, Damascus makdous, Afrin olive oil...',
    allCategories: 'All Categories (14 Sections)',
    freshColdDeliveryBadge: 'Insulated Cold Shipping for Dairy',
    freeShippingNotice: '⚡ 2-Hour Express Delivery in Greifswald (Free over 25€)',
    addToCart: 'Add to Cart',
    inStock: 'In Stock (Greifswald)',
    outOfStock: 'Out of Stock',
    piecesLeft: 'pieces left',
    quickView: 'Quick View',
    coldChain: 'Cold Chain Insulated',
    halal: '100% Halal',
    organic: 'Syrian Heritage Pantry',
    cartTitle: 'Shopping Cart',
    emptyCart: 'Your cart is currently empty',
    emptyCartDesc: 'Explore authentic Syrian imported specialties with 2-hour delivery in Greifswald!',
    subtotal: 'Subtotal',
    shipping: 'Local Greifswald Delivery',
    freeShipping: 'Free Delivery',
    freeShippingRemaining: 'Add {amount} more for free local delivery in Greifswald!',
    freeShippingAchieved: 'You earned Free 2-Hour Local Delivery! 🎁',
    coldPackagingFee: 'Insulated Cold Packaging for Dairy',
    total: 'Total',
    checkout: 'Proceed to Local Delivery Checkout',
    continueShopping: 'Continue Shopping',
    applyCoupon: 'Apply Coupon',
    couponCode: 'Promo code (try: GREIF24)',
    couponApplied: '10% Discount Applied Successfully!',
    origin: 'Syrian City of Origin',
    brand: 'Brand',
    unitWeight: 'Weight & Pack',
    ingredients: 'Ingredients',
    storageInstructions: 'Storage Instructions',
    chefAIButton: 'Chef Baraka AI 👨‍🍳',
    recipeKitsTitle: 'Syrian Recipe Bundles',
    recipeKitsSubtitle: '1-Click authentic pantry kits delivered within 2 hours in Greifswald',
    addKitToCart: 'Add All Ingredients to Cart',
    trackOrder: 'Track Order in Greifswald',
    filterBy: 'Filter by',
    sortBy: 'Sort by',
    sortDefault: 'Featured & Popular',
    sortPriceAsc: 'Price: Low to High',
    sortPriceDesc: 'Price: High to Low',
    sortRating: 'Highest Rated',
    allOrigins: 'All Syrian Cities',
    coldFilterOnly: 'Chilled items only',
    dealsOnly: 'Deals & Discounts only',
    guarantees: {
      coldDelivery: 'Fresh Cold Chain',
      coldDeliverySub: 'Thermal insulation packs to keep Syrian cheeses ice-fresh',
      fastShipping: 'Within 2 Working Hours ⚡',
      fastShippingSub: 'Direct courier delivery to your doorstep in Greifswald',
      authentic: 'Imported from Syrian Cities',
      authenticSub: 'Hama string cheeses, Afrin olive oil, Damascus coffee & sweets',
      support: 'Local WhatsApp Support',
      supportSub: 'Direct coordination with our Greifswald delivery team'
    }
  },
  de: {
    storeName: 'Barakamarkt Greifswald',
    storeSubtitle: 'Barakamarkt Greifswald - Syrische Spezialitäten & 2-Stunden-Lieferung',
    searchPlaceholder: 'Suchen nach Hama-Käse, Aleppo-Freekeh, Makdous, Afrin-Olivenöl...',
    allCategories: 'Alle Kategorien (14 Abteilungen)',
    freshColdDeliveryBadge: 'Gekühlter Frischeversand für Milchprodukte',
    freeShippingNotice: '⚡ 2-Stunden-Blitzlieferung in Greifswald (Kostenlos ab 25€)',
    addToCart: 'In den Warenkorb',
    inStock: 'Auf Lager in Greifswald',
    outOfStock: 'Ausverkauft',
    piecesLeft: 'Stück verfügbar',
    quickView: 'Schnellansicht',
    coldChain: 'Kühlketten-Lieferung',
    halal: '100% Halal',
    organic: 'Traditionell & Natürlich',
    cartTitle: 'Warenkorb',
    emptyCart: 'Ihr Warenkorb ist derzeit leer',
    emptyCartDesc: 'Entdecken Sie feine syrische Spezialitäten mit 2-Stunden-Lieferung in Greifswald!',
    subtotal: 'Zwischensumme',
    shipping: 'Lokale Greifswald-Lieferung',
    freeShipping: 'Kostenlose Lieferung',
    freeShippingRemaining: 'Noch {amount} für kostenlose Lieferung in Greifswald!',
    freeShippingAchieved: 'Sie erhalten kostenlose 2-Stunden-Lieferung! 🎁',
    coldPackagingFee: 'Kühlverpackung für Käse',
    total: 'Gesamtsumme',
    checkout: 'Zur lokalen Kasse gehen',
    continueShopping: 'Weiter einkaufen',
    applyCoupon: 'Gutschein einlösen',
    couponCode: 'Gutscheincode (z. B. GREIF24)',
    couponApplied: '10% Rabatt erfolgreich angewendet!',
    origin: 'Syrische Herkunftsstadt',
    brand: 'Marke',
    unitWeight: 'Gewicht & Einheit',
    ingredients: 'Zutaten',
    storageInstructions: 'Lagerungshinweise',
    chefAIButton: 'Chef Baraka KI 👨‍🍳',
    recipeKitsTitle: 'Syrische Rezept-Pakete',
    recipeKitsSubtitle: 'Komplette Zutaten-Sets mit 2-Stunden-Lieferung in Greifswald',
    addKitToCart: 'Alle Zutaten hinzufügen',
    trackOrder: 'Bestellung in Greifswald verfolgen',
    filterBy: 'Filtern nach',
    sortBy: 'Sortieren nach',
    sortDefault: 'Empfohlen',
    sortPriceAsc: 'Preis: Niedrig bis Hoch',
    sortPriceDesc: 'Preis: Hoch bis Niedrig',
    sortRating: 'Bestbewertet',
    allOrigins: 'Alle syrischen Städte',
    coldFilterOnly: 'Nur Kühlware',
    dealsOnly: 'Nur Sonderangebote',
    guarantees: {
      coldDelivery: 'Frische Kühlkette',
      coldDeliverySub: 'Thermoisolierte Verpackung für beste Käsequalität',
      fastShipping: 'Innerhalb von 2 Arbeitsstunden ⚡',
      fastShippingSub: 'Direkter Bote an Ihre Haustür in ganz Greifswald',
      authentic: 'Direkt aus syrischen Städten',
      authenticSub: 'Ausgewählte Delikatessen aus Hama, Aleppo, Damaskus & Afrin',
      support: 'Lokaler WhatsApp-Service',
      supportSub: 'Schnelle Abstimmung mit unserem Fahrer in Greifswald'
    }
  }
};
